import { addDoc, collection, deleteDoc, doc, getCountFromServer, getDoc, getDocs, query, serverTimestamp, Timestamp, updateDoc, where, writeBatch } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { DEFAULT_EXERCISES } from "@/data/default-exercises";
import type { BodyWeight, Exercise, PhysicalAssessment, UserProfile, Workout, WorkoutSession } from "@/types";
const all=async<T>(path:string)=> (await getDocs(collection(db,path))).docs.map(item=>({id:item.id,...item.data()}) as T);
const owned=async<T>(path:string,uid:string)=> (await getDocs(query(collection(db,path),where("ownerId","==",uid)))).docs.map(item=>({id:item.id,...item.data()}) as T);
export const usersService={list:()=>all<UserProfile>("users"),get:async(uid:string)=>{const item=await getDoc(doc(db,"users",uid));return item.exists()?item.data() as UserProfile:null;}};
export const exercisesService={list:()=>all<Exercise>("exercises"),save:(data:Omit<Exercise,"id">,id?:string)=>id?updateDoc(doc(db,"exercises",id),{...data,updatedAt:serverTimestamp()}):addDoc(collection(db,"exercises"),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}),toggle:(item:Exercise)=>updateDoc(doc(db,"exercises",item.id),{active:!item.active,updatedAt:serverTimestamp()}),remove:(id:string)=>deleteDoc(doc(db,"exercises",id)),seed:async()=>{const existing=await getDocs(collection(db,"exercises")),known=new Set(existing.docs.map(item=>item.id));let created=0,updated=0;for(let start=0;start<DEFAULT_EXERCISES.length;start+=400){const batch=writeBatch(db);for(const item of DEFAULT_EXERCISES.slice(start,start+400)){batch.set(doc(db,"exercises",item.id),{...item,updatedAt:serverTimestamp(),...(known.has(item.id)?{}:{createdAt:serverTimestamp()})},{merge:true});if(known.has(item.id))updated++;else created++;}await batch.commit()}return{created,updated,total:DEFAULT_EXERCISES.length}}};
export const workoutsService={list:()=>all<Workout>("workouts"),byUser:(uid:string)=>owned<Workout>("workouts",uid),save:(data:Omit<Workout,"id">,id?:string)=>id?updateDoc(doc(db,"workouts",id),{...data,updatedAt:serverTimestamp()}):addDoc(collection(db,"workouts"),{...data,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}),toggle:(item:Workout)=>updateDoc(doc(db,"workouts",item.id),{active:!item.active,updatedAt:serverTimestamp()}),remove:(id:string)=>deleteDoc(doc(db,"workouts",id))};
export const sessionsService={list:()=>all<WorkoutSession>("workoutSessions"),byUser:(uid:string)=>owned<WorkoutSession>("workoutSessions",uid),cancel:(id:string)=>updateDoc(doc(db,"workoutSessions",id),{status:"cancelled",endedAt:serverTimestamp()})};
export const weightsService={list:()=>all<BodyWeight>("bodyWeights"),byUser:(uid:string)=>owned<BodyWeight>("bodyWeights",uid),save:(data:Omit<BodyWeight,"id">,id?:string)=>id?updateDoc(doc(db,"bodyWeights",id),{date:data.date,weight:data.weight,note:data.note,updatedAt:serverTimestamp()}):addDoc(collection(db,"bodyWeights"),{...data,createdAt:serverTimestamp()}),remove:(id:string)=>deleteDoc(doc(db,"bodyWeights",id))};
export const assessmentsService={list:()=>all<PhysicalAssessment>("physicalAssessments"),byUser:(uid:string)=>owned<PhysicalAssessment>("physicalAssessments",uid)};
export async function dashboard(){const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),month=new Date(now.getFullYear(),now.getMonth(),1);const count=async(path:string,clauses:ReturnType<typeof where>[]=[])=>(await getCountFromServer(query(collection(db,path),...clauses))).data().count;return{users:await count("users"),exercises:await count("exercises"),workouts:await count("workouts"),completed:await count("workoutSessions",[where("status","==","completed")]),today:await count("workoutSessions",[where("startedAt",">=",Timestamp.fromDate(today))]),month:await count("workoutSessions",[where("startedAt",">=",Timestamp.fromDate(month))])};}
export async function logAction(adminUid:string,action:string,entityType:string,entityId:string,targetUserId?:string,summary?:string){try{await addDoc(collection(db,"auditLogs"),{adminUid,action,entityType,entityId,targetUserId:targetUserId??null,summary:summary??null,timestamp:serverTimestamp()});}catch(error){console.warn("Audit log não registrado.",error);}}
