"use client";
import { useEffect,useMemo,useState } from "react";
import { AdminShell } from "@/components/admin-shell";import { Card,Empty,Loading,PageTitle } from "@/components/ui";import { assessmentsService,usersService } from "@/services/data";import type { PhysicalAssessment,UserProfile } from "@/types";import { dateOnly,kg } from "@/lib/utils";
export default function AssessmentsPage(){
 const[items,setItems]=useState<PhysicalAssessment[]>([]),[users,setUsers]=useState<UserProfile[]>([]),[owner,setOwner]=useState(""),[selected,setSelected]=useState<PhysicalAssessment|null>(null);
 useEffect(()=>{Promise.all([assessmentsService.list(),usersService.list()]).then(([assessments,profiles])=>{setItems(assessments);setUsers(profiles)})},[]);
 const filtered=useMemo(()=>items.filter(item=>!owner||item.ownerId===owner).sort((a,b)=>b.date.localeCompare(a.date)),[items,owner]);const name=(uid:string)=>users.find(item=>item.uid===uid)?.name??uid;
 return <AdminShell><PageTitle eyebrow="CONSULTA" title="Avaliações físicas" detail="Dados registrados na collection physicalAssessments."/><Card><label>Usuário<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Todos</option>{users.map(item=><option key={item.uid} value={item.uid}>{item.name}</option>)}</select></label></Card>{!items.length?<Loading/>:<Card><div className="table"><div className="tr head"><span>Usuário</span><span>Data</span><span>Tipo</span><span>Ação</span></div>{filtered.map(item=><div className="tr" key={item.id}><strong>{name(item.ownerId)}</strong><span>{dateOnly(item.date)}</span><span>{item.type}</span><button className="text-button" onClick={()=>setSelected(item)}>Ver detalhes</button></div>)}</div>{!filtered.length&&<Empty>Nenhuma avaliação encontrada.</Empty>}</Card>}{selected&&<Card><div className="actions"><h2>Avaliação de {name(selected.ownerId)}</h2><button className="text-button" onClick={()=>setSelected(null)}>Fechar</button></div><div className="detail-grid"><div><small>Data</small>{dateOnly(selected.date)}</div><div><small>Tipo</small>{selected.type}</div>{selected.weight!=null&&<div><small>Peso</small>{kg(selected.weight)}</div>}{selected.height!=null&&<div><small>Altura</small>{selected.height} cm</div>}{selected.bodyFat!=null&&<div><small>Gordura corporal</small>{selected.bodyFat}%</div>}{selected.leanMass!=null&&<div><small>Massa magra</small>{kg(selected.leanMass)}</div>}</div>{Object.keys(selected.measurements??{}).length>0&&<><h2>Medidas</h2><div className="detail-grid">{Object.entries(selected.measurements).filter(([,value])=>value!=null).map(([key,value])=><div key={key}><small>{key}</small>{value} cm</div>)}</div></>}{selected.notes&&<p>{selected.notes}</p>}</Card>}</AdminShell>
}
