"use client";
import { useEffect,useMemo,useState } from "react";import { AdminShell } from "@/components/admin-shell";import { Badge,Button,Card,Loading,PageTitle } from "@/components/ui";import { exercisesService,logAction,usersService,workoutsService } from "@/services/data";import { useAdmin } from "@/components/providers";import type { Exercise,UserProfile,Workout,WorkoutExercise } from "@/types";import { dateTime,normalize } from "@/lib/utils";
export default function WorkoutsPage(){
 const{user}=useAdmin();const[items,setItems]=useState<Workout[]>([]),[users,setUsers]=useState<UserProfile[]>([]),[library,setLibrary]=useState<Exercise[]>([]),[search,setSearch]=useState(""),[owner,setOwner]=useState(""),[editing,setEditing]=useState<Workout|null|undefined>(undefined),[name,setName]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[draft,setDraft]=useState<WorkoutExercise[]>([]),[message,setMessage]=useState("");
 const reload=async()=>setItems(await workoutsService.list());
 useEffect(()=>{Promise.all([workoutsService.list(),usersService.list(),exercisesService.list()]).then(([workouts,profiles,exercises])=>{setItems(workouts);setUsers(profiles);setLibrary(exercises.filter(item=>item.active))})},[]);
 const filtered=useMemo(()=>items.filter(item=>!owner||item.ownerId===owner).filter(item=>normalize(`${item.name} ${item.title}`).includes(normalize(search))),[items,owner,search]);const userName=(uid:string)=>users.find(item=>item.uid===uid)?.name??uid;
 function open(item?:Workout){setEditing(item??null);setOwner(item?.ownerId??users[0]?.uid??"");setName(item?.name??"");setTitle(item?.title??"");setDescription(item?.description??"");setDraft(item?.exercises??[]);setMessage("")}
 function add(exercise:Exercise){if(draft.some(item=>item.exerciseId===exercise.id)){setMessage("Exercício já adicionado.");return}setDraft([...draft,{id:crypto.randomUUID(),exerciseId:exercise.id,name:exercise.name,order:draft.length+1,sets:3,repsMin:8,repsMax:12,restSeconds:90}])}
 function patch(id:string,data:Partial<WorkoutExercise>){setDraft(items=>items.map(item=>item.id===id?{...item,...data}:item))}
 async function save(event:React.FormEvent){event.preventDefault();if(!owner||!draft.length){setMessage("Selecione o usuário e ao menos um exercício.");return}const data={ownerId:owner,name:name.trim(),title:title.trim(),description:description.trim()||undefined,muscleGroups:[...new Set(draft.map(item=>library.find(e=>e.id===item.exerciseId)?.muscleGroup).filter((value):value is string=>Boolean(value)))],exercises:draft.map((item,index)=>({...item,order:index+1})),active:editing?.active??true};await workoutsService.save(data,editing?.id);if(user)await logAction(user.uid,editing?"workout.updated":"workout.created","workout",editing?.id??"new",owner,name);setEditing(undefined);setMessage("Treino salvo com sucesso.");await reload()}
 return <AdminShell>
  <PageTitle eyebrow="GESTÃO" title="Treinos" detail="Crie e administre fichas sem apagar o snapshot das sessões." action={<Button onClick={()=>open()}>+ CRIAR PARA USUÁRIO</Button>}/>
  {message&&<p className={message.includes("sucesso")?"success":"error"}>{message}</p>}
  <Card><div className="filters"><label>Pesquisar<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Usuário<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Todos</option>{users.map(item=><option value={item.uid} key={item.uid}>{item.name}</option>)}</select></label></div></Card>
  {editing!==undefined&&<Card><h2>{editing?"Editar treino":"Criar treino para usuário"}</h2><form onSubmit={save}><div className="form-grid"><label>Usuário<select required value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Selecione</option>{users.map(item=><option value={item.uid} key={item.uid}>{item.name}</option>)}</select></label><label>Nome<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Título<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Descrição<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label></div><label>Adicionar exercício<select value="" onChange={e=>{const exercise=library.find(item=>item.id===e.target.value);if(exercise)add(exercise)}}><option value="">Selecione...</option>{library.map(item=><option value={item.id} key={item.id}>{item.name} — {item.muscleGroup}</option>)}</select></label>{draft.map(item=><div className="card" key={item.id}><strong>{item.order}. {item.name}</strong><div className="form-grid"><label>Séries<input type="number" min="1" value={item.sets} onChange={e=>patch(item.id,{sets:Number(e.target.value)})}/></label><label>Repetições mín.<input type="number" min="1" value={item.repsMin} onChange={e=>patch(item.id,{repsMin:Number(e.target.value)})}/></label><label>Repetições máx.<input type="number" min="1" value={item.repsMax} onChange={e=>patch(item.id,{repsMax:Number(e.target.value)})}/></label><label>Descanso<input type="number" min="0" value={item.restSeconds} onChange={e=>patch(item.id,{restSeconds:Number(e.target.value)})}/></label></div><button type="button" className="text-button" onClick={()=>setDraft(items=>items.filter(candidate=>candidate.id!==item.id).map((candidate,index)=>({...candidate,order:index+1})))}>Remover</button></div>)}<div className="actions"><Button>SALVAR TREINO</Button><button type="button" className="text-button" onClick={()=>setEditing(undefined)}>Cancelar</button></div></form></Card>}
  <Card>{!items.length?<Loading/>:<div className="table"><div className="tr head"><span>Treino</span><span>Usuário</span><span>Status</span><span>Ações</span></div>{filtered.map(item=><div className="tr" key={item.id}><div><strong>{item.name}</strong><small>{item.exercises.length} exercícios · {dateTime(item.createdAt)}</small></div><span>{userName(item.ownerId)}</span><Badge tone={item.active?"good":"neutral"}>{item.active?"Ativo":"Arquivado"}</Badge><div className="actions"><button className="text-button" onClick={()=>open(item)}>Editar</button><button className="text-button" onClick={async()=>{await workoutsService.toggle(item);await reload()}}>{item.active?"Arquivar":"Ativar"}</button><button className="text-button" onClick={async()=>{if(confirm(`Excluir ${item.name}? As sessões antigas serão preservadas.`)){await workoutsService.remove(item.id);if(user)await logAction(user.uid,"workout.deleted","workout",item.id,item.ownerId,item.name);await reload()}}}>Excluir</button></div></div>)}</div>}</Card>
 </AdminShell>
}
