"use client";
import { useEffect,useMemo,useState } from "react";
import { AdminShell } from "@/components/admin-shell";import { Badge,Button,Card,Empty,Loading,PageTitle } from "@/components/ui";import { exercisesService,logAction,workoutsService } from "@/services/data";import { useAdmin } from "@/components/providers";import type { Exercise } from "@/types";import { errorMessage,normalize } from "@/lib/utils";
const empty={name:"",nameEn:"",aliases:"",muscleGroup:"",videoUrl:"",active:true};
export default function ExercisesPage(){
 const{user}=useAdmin();const[items,setItems]=useState<Exercise[]>([]),[search,setSearch]=useState(""),[group,setGroup]=useState(""),[editing,setEditing]=useState<Exercise|null|undefined>(undefined),[form,setForm]=useState(empty),[loading,setLoading]=useState(true),[seeding,setSeeding]=useState(false),[message,setMessage]=useState("");
 const reload=()=>exercisesService.list().then(setItems).finally(()=>setLoading(false));useEffect(()=>{void reload()},[]);
 const groups=useMemo(()=>[...new Set(items.map(item=>item.muscleGroup))].sort(),[items]);
 const filtered=useMemo(()=>items.filter(item=>!group||item.muscleGroup===group).filter(item=>normalize([item.name,item.nameEn,...(item.aliases??[])].filter(Boolean).join(" ")).includes(normalize(search))).sort((a,b)=>a.name.localeCompare(b.name,"pt-BR")),[items,search,group]);
 function open(item?:Exercise){setEditing(item??null);setForm(item?{name:item.name,nameEn:item.nameEn??"",aliases:(item.aliases??[]).join(", "),muscleGroup:item.muscleGroup,videoUrl:item.videoUrl??"",active:item.active}:empty);setMessage("")}
 async function save(event:React.FormEvent){event.preventDefault();try{await exercisesService.save({name:form.name.trim(),nameEn:form.nameEn.trim()||undefined,aliases:form.aliases.split(",").map(v=>v.trim()).filter(Boolean),muscleGroup:form.muscleGroup.trim(),videoUrl:form.videoUrl.trim()||undefined,active:form.active},editing?.id);if(user)await logAction(user.uid,editing?"exercise.updated":"exercise.created","exercise",editing?.id??"new",undefined,form.name);setEditing(undefined);setMessage("Exercício salvo com sucesso.");await reload()}catch(error){setMessage(errorMessage(error))}}
 async function remove(item:Exercise){const workouts=await workoutsService.list();if(workouts.some(workout=>workout.exercises.some(exercise=>exercise.exerciseId===item.id))){setMessage("Este exercício está referenciado por treinos. Desative-o em vez de excluir.");return}if(!confirm(`Excluir definitivamente ${item.name}?`))return;await exercisesService.remove(item.id);if(user)await logAction(user.uid,"exercise.deleted","exercise",item.id,undefined,item.name);await reload()}
 async function seed(){if(!confirm("Importar ou atualizar a biblioteca padrão de 202 exercícios? Exercícios personalizados serão preservados."))return;setSeeding(true);try{const result=await exercisesService.seed();setMessage(`Biblioteca atualizada: ${result.created} criados e ${result.updated} atualizados.`);await reload()}catch(error){setMessage(errorMessage(error))}finally{setSeeding(false)}}
 return <AdminShell>
  <PageTitle eyebrow="BIBLIOTECA" title="Exercícios" detail="A mesma collection exercises utilizada pelo aplicativo." action={<div className="actions"><Button className="secondary" onClick={()=>void seed()} disabled={seeding}>{seeding?"IMPORTANDO...":"IMPORTAR 202"}</Button><Button onClick={()=>open()}>+ NOVO EXERCÍCIO</Button></div>}/>
  {message&&<p className={message.includes("sucesso")||message.includes("atualizada")?"success":"error"}>{message}</p>}
  <Card><div className="filters"><label>Pesquisar<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, inglês ou alias"/></label><label>Grupo<select value={group} onChange={e=>setGroup(e.target.value)}><option value="">Todos</option>{groups.map(value=><option key={value}>{value}</option>)}</select></label></div></Card>
  {editing!==undefined&&<Card><h2>{editing?"Editar exercício":"Novo exercício"}</h2><form onSubmit={save}><div className="form-grid"><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Nome em inglês<input value={form.nameEn} onChange={e=>setForm({...form,nameEn:e.target.value})}/></label><label>Aliases<input value={form.aliases} onChange={e=>setForm({...form,aliases:e.target.value})}/></label><label>Grupo muscular<input required value={form.muscleGroup} onChange={e=>setForm({...form,muscleGroup:e.target.value})}/></label><label>URL do vídeo<input type="url" value={form.videoUrl} onChange={e=>setForm({...form,videoUrl:e.target.value})}/></label><label>Estado<select value={String(form.active)} onChange={e=>setForm({...form,active:e.target.value==="true"})}><option value="true">Ativo</option><option value="false">Inativo</option></select></label></div><div className="actions"><Button>SALVAR</Button><button type="button" className="text-button" onClick={()=>setEditing(undefined)}>Cancelar</button></div></form></Card>}
  {loading?<Loading/>:<Card><div className="table"><div className="tr head"><span>Exercício</span><span>Grupo</span><span>Status</span><span>Ações</span></div>{filtered.map(item=><div className="tr" key={item.id}><strong>{item.name}</strong><span>{item.muscleGroup}</span><Badge tone={item.active?"good":"neutral"}>{item.active?"Ativo":"Inativo"}</Badge><div className="actions">{item.videoUrl&&<a className="text-button" href={item.videoUrl} target="_blank" rel="noopener noreferrer">Vídeo</a>}<button className="text-button" onClick={()=>open(item)}>Editar</button><button className="text-button" onClick={async()=>{await exercisesService.toggle(item);if(user)await logAction(user.uid,item.active?"exercise.disabled":"exercise.enabled","exercise",item.id);await reload()}}>{item.active?"Desativar":"Ativar"}</button><button className="text-button" onClick={()=>void remove(item)}>Excluir</button></div></div>)}</div>{!filtered.length&&<Empty>Nenhum exercício encontrado.</Empty>}</Card>}
 </AdminShell>
}
