"use client";

import { Copy, Pencil, Plus, Power, RotateCw } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AdminShell } from "@/components/admin-shell";
import { Badge, Button, Card, Empty, Loading, PageTitle } from "@/components/ui";
import { useAdmin } from "@/components/providers";
import { logAction } from "@/services/data";
import { trainingMethodsService } from "@/services/training-methods";
import { TRAINING_METHOD_CATEGORIES, TRAINING_METHOD_CATEGORY_LABELS, TRAINING_METHOD_ENGINES, TRAINING_METHOD_ENGINE_LABELS, TRAINING_METHOD_FIELD_TYPES, TRAINING_METHOD_FIELD_TYPE_LABELS, normalTrainingMethod, snapshotMethod, validateTrainingMethod } from "@/lib/training-methods";
import { errorMessage, normalize } from "@/lib/utils";
import type { TrainingMethod, TrainingMethodConfigField, TrainingMethodConfigValue, TrainingTempo } from "@/types";

const steps = ["Identificação", "Categoria e motor", "Capacidades", "Regras", "Parâmetros", "Padrões e revisão"];
const emptyMethod = (order: number): TrainingMethod => ({ ...snapshotMethod(normalTrainingMethod()), id: `metodo-${Date.now()}`, name: "", shortDescription: "", fullDescription: "", order, system: false, active: true, version: 1 });
const clone = <T,>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const numericTypes = new Set(["number", "integer", "percentage", "seconds", "reps", "load"]);

function DefaultInput({ field, value, onChange }: { field: TrainingMethodConfigField; value: TrainingMethodConfigValue | undefined; onChange: (value: TrainingMethodConfigValue) => void }) {
  if (field.type === "boolean") return <label className="check"><input type="checkbox" checked={value === true} onChange={(event) => onChange(event.target.checked)}/>{field.label}</label>;
  if (field.type === "tempo") { const tempo = value && typeof value === "object" ? value as TrainingTempo : { eccentric: 3, pause: 0, concentric: 1, top: 0 }; return <fieldset className="tempo-admin"><legend>{field.label}</legend>{(["eccentric", "pause", "concentric", "top"] as const).map((key) => <label key={key}>{key}<input type="number" min="0" value={tempo[key]} onChange={(event) => onChange({ ...tempo, [key]: Number(event.target.value) })}/></label>)}</fieldset>; }
  if (field.type === "select") return <label>{field.label}<select value={String(value ?? "")} onChange={(event) => onChange(event.target.value)}>{field.options?.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select></label>;
  return <label>{field.label}<input type={numericTypes.has(field.type) ? "number" : "text"} min={field.min} max={field.max} value={String(value ?? "")} onChange={(event) => onChange(numericTypes.has(field.type) ? Number(event.target.value) : event.target.value)}/></label>;
}

export default function TrainingMethodsPage() {
  const { user } = useAdmin();
  const [items, setItems] = useState<TrainingMethod[]>([]);
  const [editing, setEditing] = useState<TrainingMethod | null>(null);
  const [original, setOriginal] = useState<TrainingMethod | null>(null);
  const [step, setStep] = useState(0);
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("");
  const [engine, setEngine] = useState("");
  const [status, setStatus] = useState("");
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");

  const reload = useCallback(async () => { setLoading(true); setError(""); try { setItems(await trainingMethodsService.list()); } catch (reason) { setError(errorMessage(reason)); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void reload(), 0); return () => window.clearTimeout(timer); }, [reload]);
  const filtered = useMemo(() => items.filter((item) => !category || item.category === category).filter((item) => !engine || item.engine === engine).filter((item) => !status || String(item.active) === status).filter((item) => normalize(`${item.name} ${item.shortDescription}`).includes(normalize(search))), [items, search, category, engine, status]);
  const counts = useMemo(() => ({ total: items.length, active: items.filter((item) => item.active).length, custom: items.filter((item) => !item.system).length }), [items]);
  const update = (changes: Partial<TrainingMethod>) => setEditing((item) => item ? { ...item, ...changes } : item);
  const audit = async (action: string, id: string, summary: string) => { if (user) await logAction(user.uid, action, "trainingMethod", id, summary).catch(() => setMessage("Alteração salva; o log de auditoria não pôde ser registrado.")); };

  function open(item?: TrainingMethod) { const next = item ? clone(item) : emptyMethod(items.length + 1); setEditing(next); setOriginal(item ?? null); setStep(0); setError(""); setMessage(""); }
  function addField() { if (!editing) return; const next = editing.configFields.length + 1; update({ configFields: [...editing.configFields, { key: `parametro${next}`, label: `Parâmetro ${next}`, type: "number", required: true, min: 0 }] }); }
  function updateField(index: number, changes: Partial<TrainingMethodConfigField>) { if (!editing) return; update({ configFields: editing.configFields.map((field, fieldIndex) => fieldIndex === index ? { ...field, ...changes } : field) }); }
  function removeField(index: number) { if (!editing) return; const removed = editing.configFields[index]; const defaults = { ...editing.defaults }; delete defaults[removed.key]; update({ configFields: editing.configFields.filter((_, fieldIndex) => fieldIndex !== index), defaults }); }

  async function save() {
    if (!editing) return;
    const errors = validateTrainingMethod(editing);
    if (errors.length) return setError(errors.join(" "));
    setBusy(true); setError("");
    try { const version = await trainingMethodsService.save(editing, original); await audit(original ? "trainingMethod.update" : "trainingMethod.create", editing.id, `${editing.name} v${version}`); setEditing(null); setMessage("Método salvo com sucesso."); await reload(); }
    catch (reason) { setError(errorMessage(reason)); }
    finally { setBusy(false); }
  }
  async function toggle(item: TrainingMethod) { setBusy(true); try { await trainingMethodsService.toggle(item); await audit(item.active ? "trainingMethod.deactivate" : "trainingMethod.activate", item.id, item.name); await reload(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } }
  async function duplicate(item: TrainingMethod) { setBusy(true); try { const copy = await trainingMethodsService.duplicate(item, new Set(items.map((candidate) => candidate.id))); await audit("trainingMethod.duplicate", copy.id, `${item.name} → ${copy.name}`); setMessage("Cópia criada inativa para revisão."); await reload(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } }
  async function seed() { setBusy(true); setError(""); try { const result = await trainingMethodsService.seed(); await audit("trainingMethod.seed", "system-catalog", `${result.created} criados; ${result.updated} sincronizados`); setMessage(`Catálogo sincronizado: ${result.created} criados e ${result.updated} atualizados, preservando métodos personalizados.`); await reload(); } catch (reason) { setError(errorMessage(reason)); } finally { setBusy(false); } }

  return <AdminShell><PageTitle eyebrow="CATÁLOGO GLOBAL" title="Métodos de treino" detail="Configure comportamento, parâmetros e regras sem alterar o código." action={<div className="actions"><Button className="secondary" onClick={() => void seed()} disabled={busy}><RotateCw size={15}/>SINCRONIZAR PADRÕES</Button><Button onClick={() => open()}><Plus size={15}/>NOVO MÉTODO</Button></div>}/>{message && <p className="success" role="status">{message}</p>}{error && <p className="error" role="alert">{error}</p>}
    <div className="method-metrics"><Card><span>Total</span><strong>{counts.total}</strong></Card><Card><span>Ativos</span><strong>{counts.active}</strong></Card><Card><span>Personalizados</span><strong>{counts.custom}</strong></Card></div>
    <Card><div className="method-admin-filters"><label>Pesquisar<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Nome ou descrição"/></label><label>Categoria<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">Todas</option>{TRAINING_METHOD_CATEGORIES.map((value) => <option value={value} key={value}>{TRAINING_METHOD_CATEGORY_LABELS[value]}</option>)}</select></label><label>Motor<select value={engine} onChange={(event) => setEngine(event.target.value)}><option value="">Todos</option>{TRAINING_METHOD_ENGINES.map((value) => <option value={value} key={value}>{TRAINING_METHOD_ENGINE_LABELS[value]}</option>)}</select></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos</option><option value="true">Ativos</option><option value="false">Inativos</option></select></label></div></Card>
    {editing && <Card className="method-wizard"><div className="wizard-head"><div><span className="eyebrow">ETAPA {step + 1} DE {steps.length}</span><h2>{original ? `Editar ${original.name}` : "Cadastrar método"}</h2></div><button className="text-button" onClick={() => setEditing(null)}>Fechar</button></div><div className="wizard-steps">{steps.map((label, index) => <button type="button" key={label} className={index === step ? "active" : index < step ? "done" : ""} onClick={() => setStep(index)}><b>{index + 1}</b><span>{label}</span></button>)}</div>
      {step === 0 && <div className="form-grid"><label>ID estável<input required disabled={Boolean(original)} value={editing.id} onChange={(event) => update({ id: event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-") })}/><small>Não muda após a criação.</small></label><label>Nome<input required value={editing.name} onChange={(event) => update({ name: event.target.value })}/></label><label>Descrição curta<input required value={editing.shortDescription} onChange={(event) => update({ shortDescription: event.target.value })}/></label><label>Ícone<input value={editing.iconKey} onChange={(event) => update({ iconKey: event.target.value.replace(/[^a-z0-9-]/gi, "") })}/></label><label>Ordem<input type="number" min="1" value={editing.order} onChange={(event) => update({ order: Number(event.target.value) })}/></label><label>Estado<select value={String(editing.active)} onChange={(event) => update({ active: event.target.value === "true" })}><option value="true">Ativo</option><option value="false">Inativo</option></select></label><label className="wide">Descrição completa<textarea value={editing.fullDescription} onChange={(event) => update({ fullDescription: event.target.value })}/></label></div>}
      {step === 1 && <div className="form-grid"><label>Categoria<select value={editing.category} onChange={(event) => update({ category: event.target.value as TrainingMethod["category"] })}>{TRAINING_METHOD_CATEGORIES.map((value) => <option value={value} key={value}>{TRAINING_METHOD_CATEGORY_LABELS[value]}</option>)}</select></label><label>Motor seguro<select value={editing.engine} onChange={(event) => update({ engine: event.target.value as TrainingMethod["engine"] })}>{TRAINING_METHOD_ENGINES.map((value) => <option value={value} key={value}>{TRAINING_METHOD_ENGINE_LABELS[value]}</option>)}</select></label><div className="engine-help wide"><strong>{TRAINING_METHOD_ENGINE_LABELS[editing.engine]}</strong><p>O motor define como as etapas são geradas no app. Somente motores internos auditados podem ser selecionados.</p></div></div>}
      {step === 2 && <div className="capability-grid">{Object.entries(editing.capabilities).map(([key, value]) => <label className="check" key={key}><input type="checkbox" checked={value} onChange={(event) => update({ capabilities: { ...editing.capabilities, [key]: event.target.checked } })}/>{key}</label>)}</div>}
      {step === 3 && <div className="form-grid"><label>Mínimo de exercícios<input type="number" min="1" value={editing.exerciseRules.minExercises} onChange={(event) => update({ exerciseRules: { ...editing.exerciseRules, minExercises: Number(event.target.value) } })}/></label><label>Máximo de exercícios<input type="number" min="1" value={editing.exerciseRules.maxExercises} onChange={(event) => update({ exerciseRules: { ...editing.exerciseRules, maxExercises: Number(event.target.value) } })}/></label><label className="check"><input type="checkbox" checked={editing.exerciseRules.sameMuscleGroup === true} onChange={(event) => update({ exerciseRules: { ...editing.exerciseRules, sameMuscleGroup: event.target.checked } })}/>Exigir mesmo grupo muscular</label></div>}
      {step === 4 && <div><div className="actions"><Button type="button" className="secondary" onClick={addField}><Plus size={14}/>ADICIONAR PARÂMETRO</Button></div>{editing.configFields.map((field, index) => <div className="schema-row" key={`${field.key}-${index}`}><label>Chave<input value={field.key} onChange={(event) => updateField(index, { key: event.target.value.replace(/[^a-zA-Z0-9]/g, "") })}/></label><label>Rótulo<input value={field.label} onChange={(event) => updateField(index, { label: event.target.value })}/></label><label>Tipo<select value={field.type} onChange={(event) => updateField(index, { type: event.target.value as TrainingMethodConfigField["type"] })}>{TRAINING_METHOD_FIELD_TYPES.map((value) => <option value={value} key={value}>{TRAINING_METHOD_FIELD_TYPE_LABELS[value]}</option>)}</select></label><label>Mínimo<input type="number" value={field.min ?? ""} onChange={(event) => updateField(index, { min: event.target.value === "" ? undefined : Number(event.target.value) })}/></label><label>Máximo<input type="number" value={field.max ?? ""} onChange={(event) => updateField(index, { max: event.target.value === "" ? undefined : Number(event.target.value) })}/></label>{field.type === "select" && <label>Opções (rótulo:valor)<input value={(field.options ?? []).map((item) => `${item.label}:${item.value}`).join(", ")} onChange={(event) => updateField(index, { options: event.target.value.split(",").map((item) => item.trim()).filter(Boolean).map((item) => { const [label, value = label] = item.split(":"); return { label, value }; }) })}/></label>}<button type="button" className="text-button danger-text" onClick={() => removeField(index)}>Remover</button></div>)}{!editing.configFields.length && <Empty>Nenhum parâmetro especial. O método usará somente os campos básicos.</Empty>}</div>}
      {step === 5 && <div><h3>Prescrição padrão</h3><div className="form-grid"><label>Séries<input type="number" min="1" value={Number(editing.defaults.sets ?? 3)} onChange={(event) => update({ defaults: { ...editing.defaults, sets: Number(event.target.value) } })}/></label><label>Repetições mín.<input type="number" min="0" value={Number(editing.defaults.repsMin ?? 8)} onChange={(event) => update({ defaults: { ...editing.defaults, repsMin: Number(event.target.value) } })}/></label><label>Repetições máx.<input type="number" min="0" value={Number(editing.defaults.repsMax ?? 12)} onChange={(event) => update({ defaults: { ...editing.defaults, repsMax: Number(event.target.value) } })}/></label><label>Descanso (s)<input type="number" min="0" value={Number(editing.defaults.restSeconds ?? 90)} onChange={(event) => update({ defaults: { ...editing.defaults, restSeconds: Number(event.target.value) } })}/></label><label>Carga sugerida<input type="number" min="0" step="0.1" value={Number(editing.defaults.suggestedLoad ?? 0)} onChange={(event) => update({ defaults: { ...editing.defaults, suggestedLoad: Number(event.target.value) } })}/></label></div><div className="default-grid">{editing.configFields.map((field) => <DefaultInput key={field.key} field={field} value={editing.defaults[field.key]} onChange={(value) => update({ defaults: { ...editing.defaults, [field.key]: value } })}/>)}</div><div className="review-card"><strong>{editing.name || "Método sem nome"}</strong><span>{TRAINING_METHOD_CATEGORY_LABELS[editing.category]} · {TRAINING_METHOD_ENGINE_LABELS[editing.engine]} · versão {editing.version}</span><p>{editing.shortDescription}</p><Badge tone={editing.active ? "good" : "neutral"}>{editing.active ? "Ativo" : "Inativo"}</Badge></div></div>}
      <div className="wizard-actions"><Button type="button" className="secondary" disabled={step === 0} onClick={() => setStep((value) => value - 1)}>ANTERIOR</Button>{step < steps.length - 1 ? <Button type="button" onClick={() => setStep((value) => value + 1)}>PRÓXIMA</Button> : <Button type="button" disabled={busy} onClick={() => void save()}>{busy ? "SALVANDO..." : "SALVAR MÉTODO"}</Button>}</div></Card>}
    {loading ? <Loading/> : <div className="method-card-grid">{filtered.map((item) => <Card className="method-admin-card" key={item.id}><div className="method-card-head"><div><span>{TRAINING_METHOD_CATEGORY_LABELS[item.category]}</span><h2>{item.name}</h2></div><Badge tone={item.active ? "good" : "neutral"}>{item.active ? "Ativo" : "Inativo"}</Badge></div><p>{item.shortDescription}</p><div className="method-meta"><span>{TRAINING_METHOD_ENGINE_LABELS[item.engine]}</span><span>v{item.version}</span><span>{item.system ? "Sistema" : "Personalizado"}</span><span>Ordem {item.order}</span></div><div className="actions"><button className="action-button edit-action" onClick={() => open(item)}><Pencil size={14}/>Editar</button><button className="action-button video-action" onClick={() => void duplicate(item)} disabled={busy}><Copy size={14}/>Duplicar</button><button className={`action-button ${item.active ? "disable-action" : "enable-action"}`} onClick={() => void toggle(item)} disabled={busy}><Power size={14}/>{item.active ? "Desativar" : "Ativar"}</button></div></Card>)}</div>}{!loading && !filtered.length && <Card><Empty>Nenhum método encontrado.</Empty></Card>}
  </AdminShell>;
}

